version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/minsk/src/minsk"
    schedule:
      interval: "weekly"
    # Enable security updates
    open-pull-requests-limit: 5
    commit-message:
      prefix: "deps"
    # Dependabot will also create PRs for security updates as soon as they're detected
    allow:
      - dependency-type: "all"
    ignore: []
    # This enables security updates (GitHub will trigger these automatically)
    # No explicit 'security-updates' key is needed, but schedule + the right ecosystem triggers it.
